version: '3.3'

services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api-pancrepal
    restart: always
    ports: 
      - "3600:3000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data:/data
