name: Build AI launch

on:
  push:
    paths:
      - 'src/auto-deploy/**'

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          cd src/auto-deploy
          make all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: launch
          path: |
            src/auto-deploy/deploy.json
            src/auto-deploy/launch

