name: Build AI launch

on:
  push:
    paths:
      - 'docker/auto-deploy/**'

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build binary
        run: |
          cd docker/auto-deploy
          make all

      - name: List output directory
        run: ls -l docker/auto-deploy/bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: launch
          path: docker/auto-deploy/bin/launch

